describe('tests',()=>{
    beforeEach(() => {
        // Clear cookies before each test
        cy.clearCookies();
      });
    it('mobileno. start with 5',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('5565655650')//start with 5
        cy.get('.step-danger').should('exist')
        cy.get('.p-1 > .btn').click({force:true})         
    })
    it('mobileno. start with 6',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('6565655650')//start with 6
        cy.get('.step-danger').should('not.exist')
        cy.get('.p-1 > .btn').click({force:true})         
    })
    it('mobileno. start with 7',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
        cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('7565655650')//start with 7
        cy.get('.step-danger').should('not.exist')
        cy.get('.p-1 > .btn').click({force:true})         
    })
    it('mobileno. start with 8',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
        cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('8565655650')//start with 8
        cy.get('.step-danger').should('not.exist')
        cy.get('.p-1 > .btn').click({force:true})         
    })
    it('mobileno. start with 9',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
        cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')//start with 9
        cy.get('.step-danger').should('not.exist')
        cy.get('.p-1 > .btn').click({force:true})  
    })
    it('empty otpverification',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get('#otp').type(' ')
        cy.get('#verify_otp').click({force:true})
        cy.get('.step-danger').should('exist')
    })
    it('otp with alphabets',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get('#otp').type('rryy')
        cy.get('#verify_otp').click({force:true})
        cy.get('.step-danger').should('exist')
    })
    it('otp with less numbers(3)',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
        cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get('#otp').type('123')
        cy.get('.step-danger').should('exist')
        cy.get('#verify_otp').click({force:true})
    })
    it('otp with 1 incorrect number',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get('#otp').type('1230')
        cy.get('#verify_otp').click({force:true})
        cy.get('.step-danger').should('exist')
    })
    it('valid otp(should not show any validation)',()=>{
        // cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.visit("https://php8-bajaj-loan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
        cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('pav')
        cy.get('#lname').type('ani') 
        cy.get('.p-1 > #mobile').type('9565655650')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get('#otp').type('1234')
        cy.get('.step-danger').should('not.exist')
        cy.get('#verify_otp').click({force:true})
    })
    })