describe('testcases3',()=>{
    beforeEach(() => {
        // Clear cookies before each test
        cy.clearCookies();
      });
    it('Firstname with numeric values',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('02255')
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Empty firstname',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type(' ')
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Firstname(mandatory validation check)',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        // cy.get('#fname').type(' ')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')    
    })
    it('valid firstname(should not show any validation)',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
         cy.get('#fname').type('pav')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('not.exist')    
    })
    
    it('Lastname with alphanumeric values',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('swathi')
        cy.get('#lname').type('ddd44')
        cy.get(':nth-child(13) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Lastname with numeric values',()=>{
        cy.visit("https://stage_bajajloan.cartradeexchange.com/")
        cy.get('[style="position: relative;"] > #mobile').type('9999999996')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#make').select('KTM')
        cy.get('#model').select('ADV')
        cy.get('#variant').select('390')
        cy.get('#ex_price').should('be.disabled')
        cy.get('#on_road_price').should('be.disabled')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('swathi')
        cy.get('#lname').type('02255')
        cy.get(':nth-child(13) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    
})