describe('split',()=>{
    it('valid variant',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        
        cy.get('.p-1 > .btn').click({force:true})
        
    
    })
    it('valid variant with invalid onroadprice',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300')
        cy.get(':nth-child(8) > .p-1 > .error-msg > .step-danger').should('exist')
        cy.get('.p-1 > .btn').click({force:true})
    
    })
    it('Onroadprice mandatory validation check',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        // cy.get('#on_road_price').type(' ')
        cy.get('#title').select('Mr.')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(8) > .p-1 > .error-msg > .step-danger').should('exist')
    
    })
    it('invalidonroadprice',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
         cy.get('#on_road_price').type('253164')
         cy.get(':nth-child(8) > .p-1 > .error-msg > .step-danger').should('exist')
        cy.get('#title').select('Mr.')
        cy.get('.p-1 > .btn').click({force:true})
        
    
    })
    it('valid onroad price (should not show anyvalidation)',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('290000')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(8) > .p-1 > .error-msg > .step-danger').should('not.exist')
    })
    it('selectPrefix field validation',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Select Prefix')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(10) > .p-1 > .error-msg > .step-danger').should('exist')
    })
    it('Prefix mandatory validation check',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        // cy.get('#title').select('Select Prefix')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(10) > .p-1 > .error-msg > .step-danger').should('exist') 
    })
    it('validPrefix(should not show any validation)',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
         cy.get('#title').select('Ms.')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(10) > .p-1 > .error-msg > .step-danger').should('not.exist')  
    })
    it('Firstname with alphanumeric characters',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('sdd33')
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Firstname with numeric values',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('02255')
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Empty firstname',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type(' ')
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Firstname(mandatory validation check)',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        // cy.get('#fname').type(' ')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('exist')    
    })
    it('valid firstname(should not show any validation)',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
         cy.get('#fname').type('pav')
        cy.get('.p-1 > .btn').click({force:true})
        cy.get(':nth-child(11) > .p-1 > .error-msg > .step-danger').should('not.exist')    
    })
    
    it('Lastname with alphanumeric values',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('swathi')
        cy.get('#lname').type('ddd44')
        cy.get(':nth-child(13) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    it('Lastname with numeric values',()=>{
        cy.visit('https://php8-bajaj-loan.cartradeexchange.com/')
        cy.get('[style="position: relative;"] > #mobile').type('7730066959')
        cy.get('.login100-form-btn').click({force:true})
         cy.get('#otp').type('123456')
        cy.get('.submit_button').click({force:true})
        cy.wait(1000)
        cy.get('#model').should('exist')
        cy.get('#model').select('Maxima Z')
        cy.get('#variant').select('LPG')
        cy.get('#on_road_price').type('300000')
        cy.get('#title').select('Ms.')
        cy.get('#fname').type('swathi')
        cy.get('#lname').type('02255')
        cy.get(':nth-child(13) > .p-1 > .error-msg > .step-danger').should('exist')
        // cy.get('.p-1 > .btn').click({force:true})
         
    })
    
    
})